vim.g.coc_global_extensions = {
 'coc-actions',
 'coc-symbol-line',
 'coc-clang-format-style-options',
 'coc-css',
 'coc-word',
 'coc-tag',
 'coc-lua',
 'coc-pairs',
 'coc-ltex',
 'coc-cmake',
 'coc-diagnostic',
 'coc-explorer',
 'coc-flutter-tools',
 'coc-gitignore',
 'coc-html',
 'coc-json',
 'coc-clangd',
 'coc-lists',
 'coc-marketplace',
 'coc-prettier',
 'coc-pyright',
 'coc-python',
 'coc-rls',
 'coc-rust-analyzer',
 'coc-snippets',
 'coc-sourcekit',
 'coc-stylelint',
 'coc-syntax',
 'coc-tasks',
 'coc-todolist',
 'coc-translator',
 'coc-tslint-plugin',
 'coc-tsserver',
 'coc-vimlsp',
 'coc-fzf-preview',
 'coc-highlight',
 'coc-vetur',
 'coc-yaml',
 'coc-yank'}

-- vim.cmd( [[]])
-- vim.fn.source("config.vim")
vim.cmd('source ~/.config/nvim/lua/coc/config.vim')

 vim.g.coc_snippet_next = '<tab>'
